# Generated by Django 6.1 on 2026-09-15 17:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_typedocumentfamille'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutImmobilisation',
            fields=[
                ('id_cout', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_cout', models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('FRAIS_ACQUISITION', "Frais d'acquisition"), ('ENTRETIEN', 'Entretien'), ('REPARATION', 'Réparation'), ('ASSURANCE', 'Assurance'), ('CONTROLE_TECHNIQUE', 'Contrôle technique'), ('AUTRE', 'Autre')], max_length=30)),
                ('libelle', models.CharField(max_length=255)),
                ('date_cout', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couts_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='couts', to='documents.document')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couts', to='immobilisations.immobilisation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couts_modifies', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cout_immobilisation',
                'ordering': ['-date_creation', '-id_cout'],
                'indexes': [models.Index(fields=['immobilisation', 'type_cout'], name='idx_cout_immob_type'), models.Index(fields=['immobilisation', 'statut'], name='idx_cout_immob_statut'), models.Index(fields=['date_cout'], name='idx_cout_date')],
            },
        ),
    ]
