# Generated by Django 5.2.16 on 2026-09-25 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coutimmobilisation',
            name='archive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couts_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coutimmobilisation',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coutimmobilisation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
