# Generated by Django 6.1 on 2026-09-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
        ('costs', '0001_initial'),
        ('documents', '0003_typedocumentfamille'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
        ('maintenance', '0006_rapportintervention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('DOCUMENT_EXPIRATION', 'Expiration document'), ('GARANTIE_EXPIRATION', 'Expiration garantie'), ('MAINTENANCE', 'Maintenance'), ('COUT_VALIDATION', 'Validation coût'), ('STATUT_CHANGE', 'Changement de statut'), ('AFFECTATION', 'Affectation')], max_length=50)),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('URGENT', 'Urgent')], default='INFO', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('cle_unique', models.CharField(max_length=255, unique=True)),
                ('email_envoye', models.BooleanField(default=False)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='costs.coutimmobilisation')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='documents.document')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.entreprise')),
                ('immobilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='immobilisations.immobilisation')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='maintenance.intervention')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-date_creation', '-id_notification'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='idx_notif_dest_lu'), models.Index(fields=['entreprise', 'date_creation'], name='idx_notif_entreprise_date'), models.Index(fields=['type_notification'], name='idx_notif_type')],
            },
        ),
    ]
