# Generated by Django 6.1 on 2026-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('DOCUMENT_AJOUT', 'Ajout document'), ('DOCUMENT_EXPIRATION', 'Expiration document'), ('GARANTIE_EXPIRATION', 'Expiration garantie'), ('MAINTENANCE', 'Maintenance'), ('COUT_VALIDATION', 'Validation coût'), ('STATUT_CHANGE', 'Changement de statut'), ('AFFECTATION', 'Affectation')], max_length=50),
        ),
    ]
