# Generated by Django 6.1 on 2026-09-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEntretien',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_entretien', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'type_entretien',
                'ordering': ['nom', 'id'],
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_type_entretien_code_par_entreprise')],
            },
        ),
    ]
