# Generated by Django 6.1 on 2026-09-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleEntretien',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_planification', models.CharField(choices=[('TEMPS', 'Temps'), ('USAGE', 'Usage'), ('DATE_FIXE', 'Date fixe'), ('MANUELLE', 'Manuelle')], max_length=20)),
                ('periodicite', models.PositiveIntegerField(blank=True, null=True)),
                ('unite_periodicite', models.CharField(blank=True, choices=[('JOURS', 'Jours'), ('SEMAINES', 'Semaines'), ('MOIS', 'Mois'), ('ANNEES', 'Années')], max_length=10, null=True)),
                ('seuil_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('unite_usage', models.CharField(blank=True, choices=[('KM', 'Kilomètres'), ('HEURES', 'Heures'), ('CYCLES', 'Cycles')], max_length=10, null=True)),
                ('date_fixe', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles_entretien', to='accounts.entreprise')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles_entretien', to='immobilisations.famille')),
                ('type_entretien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles_entretien', to='maintenance.typeentretien')),
            ],
            options={
                'db_table': 'modele_entretien',
                'ordering': ['nom', 'id'],
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_modele_entretien_code_par_entreprise')],
            },
        ),
    ]
