# Generated by Django 6.1 on 2026-09-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_modeleentretien'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeEntretien',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField()),
                ('obligatoire', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10)),
                ('modele_entretien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapes', to='maintenance.modeleentretien')),
            ],
            options={
                'db_table': 'etape_entretien',
                'ordering': ['ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('modele_entretien', 'ordre'), name='unique_etape_ordre_par_modele')],
            },
        ),
    ]
