# Generated by Django 6.1 on 2026-09-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
        ('maintenance', '0003_etapeentretien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('FAIBLE', 'Faible'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10)),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_demandees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='accounts.entreprise')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='immobilisations.immobilisation')),
                ('modele_entretien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='maintenance.modeleentretien')),
                ('type_entretien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='maintenance.typeentretien')),
            ],
            options={
                'db_table': 'intervention',
                'ordering': ['-date_demande', '-id'],
            },
        ),
    ]
