# Generated by Django 6.1 on 2026-09-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_intervention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviEtapeIntervention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField()),
                ('obligatoire', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('A_VALIDER', 'À valider'), ('VALIDEE', 'Validée'), ('NON_VALIDEE', 'Non validée')], default='A_VALIDER', max_length=12)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('etape_entretien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_interventions', to='maintenance.etapeentretien')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suivis_etapes', to='maintenance.intervention')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_etapes_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suivi_etape_intervention',
                'ordering': ['ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('intervention', 'ordre'), name='unique_suivi_ordre_par_intervention')],
            },
        ),
    ]
