# Generated by Django 6.1 on 2026-09-12 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_suivietapeintervention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observations', models.TextField(blank=True, default='')),
                ('travaux_realises', models.TextField()),
                ('recommandations', models.TextField(blank=True, default='')),
                ('date_rapport', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rapport', to='maintenance.intervention')),
                ('redige_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport_intervention',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
    ]
