# Generated by Django 5.2.16 on 2026-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_rapportintervention'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='etapeentretien',
            name='unique_etape_ordre_par_modele',
        ),
        migrations.AddConstraint(
            model_name='etapeentretien',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('modele_entretien', 'ordre'), name='unique_etape_ordre_par_modele'),
        ),
    ]
