# Generated by Django 6.1 on 2026-09-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_etapeentretien_unique_etape_ordre_par_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID of the event in Google Calendar', max_length=255, null=True),
        ),
    ]
