# Generated by Django 6.1 on 2026-09-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_intervention_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='est_signe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='Empreinte cryptographique de la signature électronique', max_length=255, null=True),
        ),
    ]
