# Generated by Django 6.1 on 2026-08-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.entreprise'),
        ),
    ]
