# Generated by Django 6.1 on 2026-08-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.entreprise'),
        ),
    ]
