# Generated by Django 5.2.16 on 2026-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
