# Generated by Django 6.1 on 2026-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webauthn_challenge',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
