# Generated by Django 6.1 on 2026-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_webauthn_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_face_descriptor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
