# Generated by Django 6.1 on 2026-09-27 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_ai_face_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_with_extra_permission', to='accounts.permission'),
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.permission')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission_request',
            },
        ),
    ]
