# Generated by Django 6.1 on 2026-09-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id_type_document', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('a_echeance', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_document', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'type_document',
                'ordering': ['code', 'id_type_document'],
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_type_document_code_par_entreprise')],
            },
        ),
    ]
