# Generated by Django 6.1 on 2026-09-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
        ('documents', '0001_initial'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(max_length=500, upload_to='documents/%Y/%m/')),
                ('date_document', models.DateField()),
                ('date_debut_validite', models.DateField(blank=True, null=True)),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.entreprise')),
                ('immobilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='immobilisations.immobilisation')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.typedocument')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-date_ajout', '-id'],
            },
        ),
    ]
