# Generated by Django 6.1 on 2026-09-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
        ('immobilisations', '0007_alter_immobilisation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocumentFamille',
            fields=[
                ('id_type_document_famille', models.BigAutoField(primary_key=True, serialize=False)),
                ('obligatoire', models.BooleanField(default=False)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_documents', to='immobilisations.famille')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_familles', to='documents.typedocument')),
            ],
            options={
                'db_table': 'type_document_famille',
                'constraints': [models.UniqueConstraint(fields=('type_document', 'famille'), name='unique_type_document_famille')],
            },
        ),
    ]
