# Generated by Django 5.2.16 on 2026-09-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_typedocumentfamille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_document',
        ),
    ]
