# Generated by Django 6.1 on 2026-09-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id_famille', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=500)),
                ('taux_amortissement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='ACTIVE', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'famille',
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_famille_code_par_entreprise')],
            },
        ),
    ]
