# Generated by Django 6.1 on 2026-09-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributDynamique',
            fields=[
                ('id_attribut', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('type_donnee', models.CharField(choices=[('TEXTE', 'Texte'), ('NOMBRE', 'Nombre'), ('DECIMAL', 'Décimal'), ('DATE', 'Date'), ('BOOLEEN', 'Booléen'), ('LISTE', 'Liste')], max_length=10)),
                ('obligatoire', models.BooleanField(default=False)),
                ('valeur_defaut', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('valeur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('longueur_min', models.PositiveIntegerField(blank=True, null=True)),
                ('longueur_max', models.PositiveIntegerField(blank=True, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='ACTIVE', max_length=10)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributs', to='immobilisations.famille')),
            ],
            options={
                'db_table': 'attribut_dynamique',
                'ordering': ['ordre_affichage', 'id_attribut'],
            },
        ),
    ]
