# Generated by Django 6.1 on 2026-09-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0002_attributdynamique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionAttribut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='ACTIVE', max_length=10)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='immobilisations.attributdynamique')),
            ],
            options={
                'db_table': 'option_attribut',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
