# Generated by Django 6.1 on 2026-09-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_company_permissions'),
        ('immobilisations', '0003_optionattribut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id_immobilisation', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('CREEE', 'Créée'), ('ACTIVE', 'Active'), ('EN_SERVICE', 'En service'), ('HORS_SERVICE', 'Hors service'), ('REFORMEE', 'Réformée'), ('ARCHIVEE', 'Archivée')], default='CREEE', max_length=20)),
                ('date_acquisition', models.DateField()),
                ('valeur_brute', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva_recuperable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('numero_facture', models.CharField(blank=True, max_length=100)),
                ('taux_amortissement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mode_calcul', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif')], default='LINEAIRE', max_length=20)),
                ('amortissement_anterieur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('date_fin_garantie', models.DateField(blank=True, null=True)),
                ('etat_physique', models.CharField(blank=True, max_length=100)),
                ('date_cession', models.DateField(blank=True, null=True)),
                ('prix_cession', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motif_sortie', models.CharField(blank=True, choices=[('VENTE', 'Vente'), ('MISE_AU_REBUT', 'Mise au rebut'), ('DESTRUCTION', 'Destruction'), ('DON', 'Don'), ('REMPLACEMENT', 'Remplacement'), ('AUTRE', 'Autre')], max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('date_derniere_maintenance', models.DateField(blank=True, null=True)),
                ('date_prochaine_maintenance', models.DateField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='accounts.entreprise')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='immobilisations.famille')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'immobilisation',
                'ordering': ['-date_creation', '-id_immobilisation'],
            },
        ),
    ]
