# Generated by Django 6.1 on 2026-09-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0004_immobilisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurAttribut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valeurs', to='immobilisations.attributdynamique')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_attributs', to='immobilisations.immobilisation')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valeurs_attributs', to='immobilisations.optionattribut')),
            ],
            options={
                'db_table': 'valeur_attribut',
                'constraints': [models.UniqueConstraint(fields=('immobilisation', 'attribut'), name='unique_valeur_attribut_par_immobilisation')],
            },
        ),
    ]
