# Generated by Django 6.1 on 2026-09-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0005_valeurattribut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('date_releve', models.DateField(auto_now_add=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_usage', to='immobilisations.attributdynamique')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_usage', to='immobilisations.immobilisation')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releves_usage', to='immobilisations.optionattribut')),
            ],
            options={
                'db_table': 'releve_usage',
                'ordering': ['date_releve', 'id'],
            },
        ),
    ]
