# Generated by Django 6.1 on 2026-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0006_releveusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilisation',
            name='statut',
            field=models.CharField(choices=[('CREEE', 'Créée'), ('ACTIVE', 'Active'), ('HORS_SERVICE', 'Hors service'), ('REFORMEE', 'Réformée'), ('ARCHIVEE', 'Archivée')], default='CREEE', max_length=20),
        ),
    ]
