# Generated by Django 5.2.16 on 2026-09-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0007_alter_immobilisation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='icone',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='familles/icones/'),
        ),
    ]
