# Generated by Django 5.2.16 on 2026-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0008_alter_famille_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releveusage',
            name='date_releve',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
